<h1> Markov Chain analysis of transport systems. </h1>

<h2> Creating a fake transport network </h2>

In [10]:
import numpy as np
"""
What we are doing is creating a set of base nodes and then we will sub divide
the arcs from  to form a more complex fake network that roughly mimics a real network.
Each of these base nodes represent a change over between routes, and is connected to atleast 3 other base nodes.
"""
NumberOfBaseNodes = 5
BaseMatrix = np.zeros((4,4))
BaseMatrix.fill(2)
print(BaseMatrix)
print([1 for i in range(BaseMatrix.shape[0])])
np.append(BaseMatrix , [1 for i in range(BaseMatrix.shape[0])] , axis = 0)
np.append(BaseMatrix , [1 for i in range(BaseMatrix.shape[1])] , axis = 1)


[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[1, 1, 1, 1]


ValueError: all the input arrays must have same number of dimensions

In [15]:
def MakeRowstochastic(InputMatrix):
    """
    Takes in a matix and makes it row stochastic
    Matrix must be a numpy matrix.
    TODO figure out if this function is functionally pure
    """
    AverageVector = np.sum(InputMatrix , axis = 1) # Find the row average
    Output = InputMatrix  / AverageVector[: , None]  #divide each of the rows by the row average.
    return Output


Input = np.array([[1,2],[2,5]])

Input = MakeRowstochastic(Input)
print(Input)


[[0.33333333 0.66666667]
 [0.28571429 0.71428571]]
